IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS C WHERE C.TABLE_NAME='details' AND C.COLUMN_NAME='Is_ETL_Enabled')
BEGIN
  ALTER TABLE dbo.details ADD Is_ETL_Enabled INT NOT NULL DEFAULT 0;
END;
GO